#!/usr/bin/env python3
"""Query the ecd dictionary database.

Usage:
  ecd                       Enter interactive mode
  ecd <word>                Search both dictionaries for English word
  ecd <chinese-text>        Reverse lookup: search Chinese for English entries
  ecd -s collins <word>     Search Collins only
  ecd -s oxford <word>      Search Oxford only
"""

from ecdlib import main

main()
